### ISSUE TITLE
Prevent socket.inet_pton override on Python3

### ISSUE THREAD

**Issue by justengel** [hickeroar/win_inet_pton#7]
I am using win_inet_pton for compatibility with Python 2.7. I am always getting a socket.error(ctypes.FormatError()) exception while running on windows 10 with Python3.4, 3.5 and 3.6. The Python 3 socket library on windows comes with the inet_pton and inet_ntop functions. Prevent overriding the default function for Python 3.

```python
# Adding our two functions to the socket library
if not hasattr(socket, 'inet_pton') and os.name == 'nt':
    socket.inet_pton = inet_pton
    socket.inet_ntop = inet_ntop
```

**Comment by sethmlarson** [comment]
Thanks for opening this issue! This will be fixed in #5.
